# GitHub Pages Configuration for LCOJ Tools

# Site settings
title: "LCOJ Tools"
description: "A comprehensive collection of web development utilities designed to boost productivity and streamline common tasks."
baseurl: ""
url: "https://tools.behitek.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Custom domain
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - html-to-image/start-server.bat
  - html-to-image/start-server.sh
  - html-to-image/server.py
  - html-to-image/AGENTS.md

# Include files
include:
  - _redirects

# SEO and social
author: "LCOJ Tools Team"
twitter:
  username: lcoj_tools
  card: summary_large_image

# Analytics (optional - add your tracking IDs)
google_analytics: 
# google_site_verification: 

# Collections
collections:
  tools:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"
